DROP DATABASE IF EXISTS ADOPET;

CREATE DATABASE ADOPET CHARACTER SET='UTF8' COLLATE='UTF8_GENERAL_CI';

USE ADOPET;

CREATE TABLE IF NOT EXISTS TB_USER(
ID_USER INT NOT NULL AUTO_INCREMENT,
NM_USER VARCHAR (60),
CPF_USER VARCHAR (50),
CIDADE_USER VARCHAR (50),
EMAIL_USER VARCHAR (60),
SENHA_USER VARCHAR (180),
SEXO_USER VARCHAR(80),
PRIMARY KEY (ID_USER)
);

CREATE TABLE IF NOT EXISTS TB_TUTOR(
CD_TUTOR INT NOT NULL AUTO_INCREMENT,
NM_INSTITUICAO VARCHAR (60),
CNPJ_TUTOR VARCHAR (50),
CIDADE_TUTOR VARCHAR (50),
NUM_TUTOR VARCHAR (50),
EMAIL_TUTOR VARCHAR (60),
SENHA_TUTOR VARCHAR (180),
PRIMARY KEY (CD_TUTOR)
);

CREATE TABLE IF NOT EXISTS TB_PET(
CD_PET INT NOT NULL AUTO_INCREMENT,
ID_USER INT,
NM_PET VARCHAR (60),
SEXO VARCHAR(80), 
NASC_PET DATE,
RACA VARCHAR (60),
PORTE VARCHAR (60),
CASTRADO VARCHAR (60),
DATE_PUB CHAR(10),
IMG_PET LONGTEXT,
PRIMARY KEY (CD_PET),
FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID_USER)
);